name: solution-operations

on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  pull_request:
    branches: [ main ]

jobs:
  crud:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      WF_USERNAME: sbhalgat@ppdevtools.onmicrosoft.com

    steps:
    - name: Check if long paths are enabled
      shell: pwsh
      run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
    
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      id: unpack-solution-test
      with:
        solution-file: \\?\${{ github.workspace }}\a\Test-Github-Pipeline\Test-Github-Pipeline\out\testetestetestetestetesttestetsetestetestetestetestetestetestetestetestetestetestetestetestetestetesteteststetestetestetestetesteteste\factoidSolution.zip
        solution-folder: \\?\${{ github.workspace }}\a\poweractionslab\poweractionslab\a\Test-Github-Pipeline\Test-Github-Pipeline\out\testetestetestetestetesttestetsetestetestetestetestetestetestetestetestetestetestetestetestetestetesteteststetestetestetestetesteteste\factoidSolution
